version: '3.1'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: pwroot
    ports:
        - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/dbConfig:/etc/mysql/conf.d
  
  backupdb:
    image: fradelg/mysql-cron-backup
    depends_on:
      - db
    restart: always
    volumes:
      - db:/backup
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=pwroot
      - MYSQL_DATABASE=wp
      - CRON_TIME=0 0 * * *
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - TIMEOUT=10s
      - INIT_BACKUP=1
      - GZIP_LEVEL=9

  wordpress:
    depends_on:
      - db
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: always
    ports:
      - '9000:9000'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wp
      WORDPRESS_TABLE_PREFIX: wp_

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - wordpress
volumes:
  db:
