version: '3.2'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${mysql_db}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_pw}
      MYSQL_ROOT_PASSWORD: ${mysql_root_pw}
    volumes:
      - mysql_db:/var/lib/mysql

  wordpress:
    depends_on:
      - mysql
    image: wordpress:fpm-alpine
    # build:
    #   context: ./
    container_name: wordpress
    restart: always
    ports:
      - '9000:9000'
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${mysql_user}
      WORDPRESS_DB_PASSWORD: ${mysql_pw}
      WORDPRESS_DB_NAME: ${mysql_db}
      WORDPRESS_TABLE_PREFIX: wp_
      # WAIT_HOSTS: mysql:3306
    volumes:
      - wp:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    environment: 
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - wp:/var/www/html
    links:
      - wordpress

volumes:
  mysql_db:
  wp:
