version: '3.2'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: /run/secrets/mysql_db_secret
      MYSQL_USER: /run/secrets/mysql_user_secret
      MYSQL_PASSWORD: /run/secrets/mysql_pw_secret
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_pw_secret
    volumes:
      - mysql_db:/var/lib/mysql
    secrets:
      - mysql_db_secret
      - mysql_user_secret
      - mysql_pw_secret
      - mysql_root_pw_secret

  wordpress:
    depends_on:
      - mysql
    image: wordpress:v1
    build:
      context: ./
    container_name: wordpress
    restart: always
    ports:
      - '9000:9000'
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: /run/secrets/mysql_user_secret
      WORDPRESS_DB_PASSWORD: /run/secrets/mysql_pw_secret
      WORDPRESS_DB_NAME: /run/secrets/mysql_db_secret
      WORDPRESS_TABLE_PREFIX: wp_
      WAIT_HOSTS: mysql:3306
    volumes:
      - wp:/var/www/html
    secrets:
      - mysql_db_secret
      - mysql_pw_secret
      - mysql_user_secret

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - wp:/var/www/html
    links:
      - wordpress

volumes:
  mysql_db:
  wp:
secrets:
  mysql_db_secret:
    file: db.txt
  mysql_pw_secret:
    file: pw.txt
  mysql_root_pw_secret:
    file: root.txt
  mysql_user_secret:
    file: user.txt
 