version: 2.0
jobs:
  build:
    branches:
      only:
        - master
    machine: true
    steps:
      - checkout
      - run:
          name: "test docker-compose"
          command: |
            docker-compose up -d
