version: 2.0
jobs:
  build:
    branches:
      only:
        - dev
        - master
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "test docker-compose"
          command: docker-compose up -d
      # - run: sleep 60
      - run:
          name: "test website avaliability"
          command: |
            res=`curl localhost:8080`
            if [ "$?" -ne 0 ]
            then
              exit 1
            fi

            if [ "$res" -eq "404 page not found" ]
            then
              exit 1
            fi