version: 2.1

orbs:
  gh: circleci/github-cli@1.0.2

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Test docker-compose build"
          command: docker-compose up -d
      - run: sleep 100
      - run:
          name: "Test database connection"
          command: docker exec $(docker ps -f name=mysql -q) mysql -u root -p$mysql_root_pw
      # - run:
      #     name: "Test website availability"
      #     command: |
      #       res=`curl localhost:8080`

      #       if [ "$?" -ne 0 ]
      #       then
      #         exit 1
      #       fi

      #       if [ "$res" = "404 page not found" ]
      #       then
      #         exit 1
      #       fi
      - gh/setup
      - run:
          name: "Create new pull request"
          command: |
            msg=`git log -1 --pretty=format:"Latest Commit: %s"`
            gh pr create --title "New pull request from dev" --body "$msg" || echo "No need to create a new pull request."
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8a:45:83:7c:a1:87:b2:cd:cc:1e:f9:f1:d5:1a:4b:21"
      - run:
          name: Deploy to lightsail staging server
          command: |
            ssh $SSH_USER@$SSH_HOST \
            "echo deploy starting && \
            cd wordpress && \
            cd pipeline && \
            git checkout dev && \
            git pull && \ 
            sudo docker-compose up -d && \
            echo deploy finished"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
          # filters:
          #   branches:
          #     only: master
          #     only: dev
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
              # only: dev