version: 2.0
jobs:
  build:
    branches:
      only:
        - dev
        - master
    machine: true
    steps:
      - checkout
      - run:
          name: "test docker-compose"
          command: docker-compose up -d
      - run: curl localhost:8080
