version: 2.0
#Test circleCI auto buid
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "test docker-compose"
          command: |
            docker-compose up -d
            docker container exec backup ls /backup/ -name "*.wp.sql.gz"
