version: 2.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "test docker-compose build"
          command: docker-compose up -d
      - run: sleep 100
      - run:
          name: "test database connection"
          command: docker exec $(docker ps -f name=mysql -q) mysql -u root -p$mysql_root_pw
      - run:
          name: "test website avaliability"
          command: |
            res=`curl localhost:8080`

            if [ "$?" -ne 0 ]
            then
              exit 1
            fi

            if [ "$res" = "404 page not found" ]
            then
              exit 1
            fi
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8a:45:83:7c:a1:87:b2:cd:cc:1e:f9:f1:d5:1a:4b:21"
      - run:
          name: lightsail stage server delploy  
          command: |
            ssh ubuntu@54.206.184.206 \
            "echo deploy starting && \
            cd wordpress && \
            cd pipeline && \
            git checkout dev && \
            git pull && \ 
            sudo docker-compose up -d && \
            curl localhost:8080 && \
            echo depoly finished"


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

